#!/bin/bash
### ---
### name: 'NFCORE_SAREK:SAREK:MULTIQC (sarek)'
### container: 'community.wave.seqera.io/library/multiqc:1.35--839587b417d23042'
### outputs:
### - '*.html'
### - '*_data'
### - '*_plots'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status grep -E 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | grep -E 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}

nxf_stat() {
    cpu_stat=()
    nxf_tree $1

    declare -a sum=(0 0 0 0 0 0 0 0)
    local pid
    local i
    for pid in "${!cpu_stat[@]}"; do
        local row=(${cpu_stat[pid]})
        [ $NXF_DEBUG = 1 ] && echo "++ stat mem=${row[*]}"
        for i in "${!row[@]}"; do
        if [ $i != 0 ]; then
            sum[i]=$((sum[i]+row[i]))
        fi
        done
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat SUM=${sum[*]}"

    for i in {1..7}; do
        if [ ${sum[i]} -lt ${cpu_peak[i]} ]; then
            sum[i]=${cpu_peak[i]}
        else
            cpu_peak[i]=${sum[i]}
        fi
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat PEAK=${sum[*]}\n"
    nxf_stat_ret=(${sum[*]})
}

nxf_mem_watch() {
    set -o pipefail
    local pid=$1
    local trace_file=.command.trace
    local count=0;
    declare -a cpu_stat=(0 0 0 0 0 0 0 0)
    declare -a cpu_peak=(0 0 0 0 0 0 0 0)
    local mem_tot=$(< /proc/meminfo grep MemTotal | awk '{print $2}')
    local timeout
    local DONE
    local STOP=''

    [ $NXF_DEBUG = 1 ] && nxf_sleep 0.2 && ps fx

    while true; do
        nxf_stat $pid
        if [ $count -lt 10 ]; then timeout=1;
        elif [ $count -lt 120 ]; then timeout=5;
        else timeout=30;
        fi
        read -t $timeout -r DONE || true
        [[ $DONE ]] && break
        if [ ! -e /proc/$pid ]; then
            [ ! $STOP ] && STOP=$(nxf_date)
            [ $(($(nxf_date)-STOP)) -gt 10000 ] && break
        fi
        count=$((count+1))
    done

    printf "%s\n" \
        "%mem=${nxf_stat_ret[1]}" \
        "vmem=${nxf_stat_ret[2]}" \
        "rss=${nxf_stat_ret[3]}" \
        "peak_vmem=${nxf_stat_ret[4]}" \
        "peak_rss=${nxf_stat_ret[5]}" \
        "vol_ctxt=${nxf_stat_ret[6]}" \
        "inv_ctxt=${nxf_stat_ret[7]}" >> "$trace_file" || >&2 echo "Error: Failed to append to file: $trace_file"
}

nxf_write_trace() {
    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"
}

nxf_trace_mac() {
    local start_millis=$(nxf_date)

    /usr/bin/env bash -C -e -u -o pipefail /Users/stav/repos/nf-tui/work/2e/3330dc0be720e3cedeb1c1b1454198/.command.sh

    local end_millis=$(nxf_date)
    local wall_time=$((end_millis-start_millis))
    local ucpu=''
    local cpu_model=''
    local io_stat1=('' '' '' '' '' '')
    nxf_write_trace
}

nxf_fd() {
    local FD=11
    while [ -e /proc/$$/fd/$FD ]; do FD=$((FD+1)); done
    echo $FD
}

nxf_trace_linux() {
    local pid=$$
    command -v ps &>/dev/null || { >&2 echo "Command 'ps' required by nextflow to collect task metrics cannot be found"; exit 1; }
    local num_cpus=$(< /proc/cpuinfo grep '^processor' -c)
    local cpu_model=$(< /proc/cpuinfo grep '^model name' | head -n 1 | awk 'BEGIN{FS="\t: "} { print $2 }')
    local tot_time0=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time0=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local io_stat0=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local start_millis=$(nxf_date)
    trap 'kill $mem_proc' ERR
    
    /usr/bin/env bash -C -e -u -o pipefail /Users/stav/repos/nf-tui/work/2e/3330dc0be720e3cedeb1c1b1454198/.command.sh &
    local task=$!

    mem_fd=$(nxf_fd)
    eval "exec $mem_fd> >(nxf_mem_watch $task)"
    local mem_proc=$!

    wait $task

    local end_millis=$(nxf_date)
    local tot_time1=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time1=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local ucpu=$(awk -v p1=$cpu_time1 -v p0=$cpu_time0 -v t1=$tot_time1 -v t0=$tot_time0 -v n=$num_cpus 'BEGIN { pct=(p1-p0)/(t1-t0)*100*n; printf("%.0f", pct>0 ? pct : 0) }' )

    local io_stat1=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local i
    for i in {0..5}; do
        io_stat1[i]=$((io_stat1[i]-io_stat0[i]))
    done

    local wall_time=$((end_millis-start_millis))
    [ $NXF_DEBUG = 1 ] && echo "+++ STATS %CPU=$ucpu TIME=$wall_time I/O=${io_stat1[*]}"

    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"

    [ -e /proc/$mem_proc ] && eval "echo 'DONE' >&$mem_fd" || true
    wait $mem_proc 2>/dev/null || true
    while [ -e /proc/$mem_proc ]; do nxf_sleep 0.1; done
}

nxf_trace() {
    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}
# aws cli retry config
export AWS_RETRY_MODE=standard
export AWS_MAX_ATTEMPTS=5
# aws helper
nxf_s3_upload() {
    local name=$1
    local s3path=$2
    if [[ "$name" == - ]]; then
      aws s3 cp --only-show-errors --storage-class STANDARD - "$s3path"
    elif [[ -d "$name" ]]; then
      aws s3 cp --only-show-errors --recursive --storage-class STANDARD "$name" "$s3path/$name"
    else
      aws s3 cp --only-show-errors --storage-class STANDARD "$name" "$s3path/$name"
    fi
}

nxf_s3_download() {
    local source=$1
    local target=$2
    local file_name=$(basename $1)
    local is_dir=$(aws s3 ls $source | grep -F "PRE ${file_name}/" -c)
    if [[ $is_dir == 1 ]]; then
        aws s3 cp --only-show-errors --recursive "$source" "$target"
    else
        aws s3 cp --only-show-errors "$source" "$target"
    fi
}
nxf_container_env() {
cat << EOF
export PYTHONNOUSERSITE="1"
export R_PROFILE_USER="/.Rprofile"
export R_ENVIRON_USER="/.Renviron"
export JULIA_DEPOT_PATH="/usr/local/share/julia"
export PATH="\$PATH:/Users/stav/.nextflow/assets/.repos/nf-core/sarek/clones/b97952e5bac68d5deb93d4a3349a45f146be9830/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /Users/stav/repos/nf-tui/work/2e/3330dc0be720e3cedeb1c1b1454198/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 4096 --memory 12288m -e "NXF_TASK_WORKDIR" -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /Users/stav:/Users/stav -w "$NXF_TASK_WORKDIR" -u $(id -u):$(id -g) --name $NXF_BOXID community.wave.seqera.io/library/multiqc:1.35--839587b417d23042 /bin/bash -c "eval $(nxf_container_env); bash -C -e -u -o pipefail /Users/stav/repos/nf-tui/work/2e/3330dc0be720e3cedeb1c1b1454198/.command.run nxf_trace"
}

nxf_stage() {
    true
    # stage input files
    rm -f 15/test.strelka.variants.bcftools_stats.txt
    rm -f 17/test.strelka.variants.TsTv.count
    rm -f 5/test-test_L2_1_fastqc.zip
    rm -f 3/test-test_L1_1_fastqc.zip
    rm -f 18/test.strelka.variants.FILTER.summary
    rm -f 13/test.recal.mosdepth.global.dist.txt
    rm -f 10/test.md.cram.stats
    rm -f 1/multiqc_config.yml
    rm -f 19/nf_core_sarek_software_mqc_versions.yml
    rm -f 8/test.md.mosdepth.region.dist.txt
    rm -f 14/test.recal.cram.stats
    rm -f 16/test.strelka.variants.TsTv.qual
    rm -f 2/workflow_summary_mqc.yaml
    rm -f 11/test.recal.table
    rm -f 1/methods_description_mqc.yaml
    rm -f 4/test-test_L1_2_fastqc.zip
    rm -f 12/test.recal.mosdepth.region.dist.txt
    rm -f 7/test.md.cram.metrics
    rm -f 6/test-test_L2_2_fastqc.zip
    rm -f 9/test.md.mosdepth.global.dist.txt
    mkdir -p 15 && ln -s /Users/stav/repos/nf-tui/work/40/c0df0cceb4466f4c7fdd3a46329d5a/test.strelka.variants.bcftools_stats.txt 15/test.strelka.variants.bcftools_stats.txt
    mkdir -p 17 && ln -s /Users/stav/repos/nf-tui/work/70/0ea3f7fcc14c87771a6e6eb23cf03d/test.strelka.variants.TsTv.count 17/test.strelka.variants.TsTv.count
    mkdir -p 5 && ln -s /Users/stav/repos/nf-tui/work/11/2634ad7a2193105c273c515eeef219/test-test_L2_1_fastqc.zip 5/test-test_L2_1_fastqc.zip
    mkdir -p 3 && ln -s /Users/stav/repos/nf-tui/work/18/fb192ebc70f1a0e8c764d278c7f4d2/test-test_L1_1_fastqc.zip 3/test-test_L1_1_fastqc.zip
    mkdir -p 18 && ln -s /Users/stav/repos/nf-tui/work/32/ad9c9d8d7a94cf84e0b293df575a22/test.strelka.variants.FILTER.summary 18/test.strelka.variants.FILTER.summary
    mkdir -p 13 && ln -s /Users/stav/repos/nf-tui/work/29/386339e76ae38ebe1f4eea1d9cde9d/test.recal.mosdepth.global.dist.txt 13/test.recal.mosdepth.global.dist.txt
    mkdir -p 10 && ln -s /Users/stav/repos/nf-tui/work/33/cb2bcd8dda12f405c65012ffbf9f5c/test.md.cram.stats 10/test.md.cram.stats
    mkdir -p 1 && ln -s /Users/stav/.nextflow/assets/.repos/nf-core/sarek/clones/b97952e5bac68d5deb93d4a3349a45f146be9830/assets/multiqc_config.yml 1/multiqc_config.yml
    mkdir -p 19 && ln -s /Users/stav/repos/nf-tui/out/pipeline_info/nf_core_sarek_software_mqc_versions.yml 19/nf_core_sarek_software_mqc_versions.yml
    mkdir -p 8 && ln -s /Users/stav/repos/nf-tui/work/51/d448755656e78cb035c07b6a9e69ba/test.md.mosdepth.region.dist.txt 8/test.md.mosdepth.region.dist.txt
    mkdir -p 14 && ln -s /Users/stav/repos/nf-tui/work/98/9ba4fe86538fbbe117a25091894d1b/test.recal.cram.stats 14/test.recal.cram.stats
    mkdir -p 16 && ln -s /Users/stav/repos/nf-tui/work/50/f85d7397a1fa31dbf5464c7e367e33/test.strelka.variants.TsTv.qual 16/test.strelka.variants.TsTv.qual
    mkdir -p 2 && ln -s /Users/stav/repos/nf-tui/work/tmp/1b/399c30d10d703d0def6642c0093fed/workflow_summary_mqc.yaml 2/workflow_summary_mqc.yaml
    mkdir -p 11 && ln -s /Users/stav/repos/nf-tui/work/4e/93d83ece108cf51a08ac99179b63d0/test.recal.table 11/test.recal.table
    mkdir -p 1 && ln -s /Users/stav/repos/nf-tui/work/tmp/bf/d587b79650b9248262ced830d130b7/methods_description_mqc.yaml 1/methods_description_mqc.yaml
    mkdir -p 4 && ln -s /Users/stav/repos/nf-tui/work/18/fb192ebc70f1a0e8c764d278c7f4d2/test-test_L1_2_fastqc.zip 4/test-test_L1_2_fastqc.zip
    mkdir -p 12 && ln -s /Users/stav/repos/nf-tui/work/29/386339e76ae38ebe1f4eea1d9cde9d/test.recal.mosdepth.region.dist.txt 12/test.recal.mosdepth.region.dist.txt
    mkdir -p 7 && ln -s /Users/stav/repos/nf-tui/work/f8/ae3978b1e92afe3cb18d7e70301a55/test.md.cram.metrics 7/test.md.cram.metrics
    mkdir -p 6 && ln -s /Users/stav/repos/nf-tui/work/11/2634ad7a2193105c273c515eeef219/test-test_L2_2_fastqc.zip 6/test-test_L2_2_fastqc.zip
    mkdir -p 9 && ln -s /Users/stav/repos/nf-tui/work/51/d448755656e78cb035c07b6a9e69ba/test.md.mosdepth.global.dist.txt 9/test.md.mosdepth.global.dist.txt
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/stav/repos/nf-tui/work/2e/3330dc0be720e3cedeb1c1b1454198/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
